### ISSUE TITLE
Feature: Send-to-Many (Tip integration)

### ISSUE THREAD

**Issue by NukeManDan** [austintgriffith/burner-wallet#103]
From @ethdenver, @crisgarner and I worked on this project: https://github.com/AffogatoNetwork/splitter

The inspiration was a need for tipping a party other and the vendor I am receiving from directly (for Affogato, this was buying coffee and tipping the coffee farmer in another country) 

Generalizing that, we want to integrate a on-to-many payment method, so one could pay for all services, products, fees, and taxes to one (or many) addresses, and also optionally add a tip (to one or many parties)

The flow could be simple as a user: a single scan of a pre-generated QE would have all information:
- items / services + prices
- address(es) to send funds to
- option to add a tip

Thus scan -> confirm -> submit flow is fluid and only one on-chain tx needs to take place because we use a "splitter" contract to send funds to many places, vs. a tx per recipient.

**Comment by NukeManDan** [comment]
I have a simple UI wireframe and flow diagram together and would love some feedback:

![image](https://user-images.githubusercontent.com/35669742/53287505-46627800-373a-11e9-9372-91ffae423caa.png)
Edit this file [here](https://www.draw.io/#HNukeManDan%2Fdraw.io%2Fmaster%2Fburner_tip_flow.xml)
Source [here](https://github.com/NukeManDan/draw.io)

**Comment by crisgarner** [comment]
Two use cases that I see from ETH Denver exercise. First is adding tips, most of the trucks after a day had a sign saying that they will take tips on buffidais. Second, multi items/transactions buy. It was easy since most meals were 8, but if you had a variable menu with different prices could start getting messy.

Maybe the solution for this, isn't on the burner wallet, but maybe on a "burner pos" for pop up events.
