### ISSUE TITLE
Button on "Bank Account or Credit Card" screen does not work on iOS safari on iPhone SE 

### ISSUE THREAD

**Issue by jtremback** [austintgriffith/burner-wallet#60]
Nothing happens when you press it

**Comment by jtremback** [comment]
I'm referring to the Create/Connect button btw @austintgriffith

**Comment by austintgriffith** [comment]
Yeah I know these don't work yet. We are working closely with Wyre to create better ramps. For now to off/onramp you have to go to the service like coinbase, get your off-ramp address, come back to the burner and use the blue-right-arrow send button. 

I was going to document this process and have it show up when you hit the button, but it sucks and I think we can do better. That's why i'm just keeping the buttons like that for now while I wait for Wyre to build out the product we need. Look for an update on this in a few weeks!

**Comment by jtremback** [comment]
Ok, cool thanks. Was just going to tell you about a few other phones where it doesn't work but it sounds like you've got it under control. Maybe remove them to avoid confusing people.

**Comment by austintgriffith** [comment]
Good call, deploying a quick update to add some feedback to those buttons for now to avoid confusion.
