### ISSUE TITLE
Token SC is not compiling.

### ISSUE THREAD

**Issue by riusricardo** [austintgriffith/burner-wallet#62]
There is a missing variable in the Token SC.
`Undeclared identifier: _balances[msg.sender] ...
`

The reason for this to happen is related to some changes in Openzeppelin SC introduced for the 2.0.0 version. In this case it is affected by a private variable instead of a previous internal variable definition.

In `openzeppelin-solidity/contracts/token/ERC20/ERC20.sol` in line 17 the _balances variable is defined as private.
Private variables can't be inherited or accessed from child SCs. Internal variables can be.

Changing the variable defintion from private to internal, fixes the issue.
```
mapping (address => uint256) private _balances;
to
mapping (address => uint256) internal _balances;
```

**Comment by alexfisher** [comment]
Also mentioned in issue #56

**Comment by riusricardo** [comment]
Thanks @alexfisher , I didn't see the previous issue #56

**Comment by riusricardo** [comment]
Just as a comment to the issue #56, removing the private definition and not changing it to internal will default it to public. Probably not super insecure but there is a public function (balanceOf) to get the actual balance so there is no need to keep it public.

**Comment by dbe** [comment]
That contract really shouldn't even be checked into master tbh. Its a work in progress which should be in a branch, or at least not involved in the main test suite yet.

Don't worry about security or code for that contract because it doesn't look even remotely like it will once we actually get it to a production ready state. 

If you are having test blocking issues I'd just suggest hacking around it to get whatever you need to get done. I'll get this taken care of today so it doesn't block people going forward.

**Comment by riusricardo** [comment]
@dbe The contract is in production releases openzeppelin-solidity@2.0.0 (Solidity 0.4.24)
It is also available in the latest release openzeppelin-solidity@2.1.1 (Solidity 0.5.0)

**Comment by dbe** [comment]
@riusricardo 

Ah, sorry I don't think I got across what I meant to. You are totally right about the BalanceOf function and fix. 

What I meant is that the DenDai contract currently in the BurnerWallet was put in master a bit prematurely I think. This normally wouldn't be too bad, but because the current test suite breaks if any one thing breaks, and the test suite is the current way to deploy contracts locally, it is causing these issues.

I was just suggesting not to worry too much about the specifics of that contract or implementation yet, as it is basically a quick implementation for testing UI. I'm working on the more final version of the SC here: [Link](https://github.com/dbe/burner-wallet/tree/master/contracts/VendingMachine)

**Comment by riusricardo** [comment]
Closing because the OpenZeppelin libraries are now part of the repo. No more need to track this issue.

**Comment by riusricardo** [comment]
I agree. But the fix breaks no compatibility with the ERC20 token. Changing to internal instead of private could be a permanent fix. OZ has that variable as private in new releases.
The ERC20 contract with the fix could be the only one that we should keep in the repo.

**Comment by dbe** [comment]
With the new smart contract there is no need to have it be internal. We are using the contract APIs as intended with the new stuff.

**Comment by riusricardo** [comment]
I'm not getting what you mean with "new smart contract". Are you working on a new PR?
If not, I'll take another look later and work in some upgrades.

**Comment by riusricardo** [comment]
@dbe  I see thew new contract branch. https://github.com/austintgriffith/burner-wallet/blob/new-vend/contracts/ERC20Vendable/ERC20Vendable.sol
